apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-app
  labels:
    app: billing-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      containers:
      - name: billing-app
        image: klevi730/billing-app:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: billing-app-configs
        - secretRef:
            name: billing-app-secrets
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
